<a href="https://colab.research.google.com/github/BIM-Master/Hotel-Reviews/blob/Sam-end-of-day-27-may/Hotel_reviews_27_may.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.4)

In [3]:
import nltk

In [4]:
from nltk.tokenize import word_tokenize

In [5]:
import pandas as pd

In [10]:
Hotel_df = pd.read_csv("/content/Hotel_Reviews 2 (1).csv")

Removing attributes

In [11]:
columns_to_remove = ["Hotel_Address", "Additional_Number_of_Scoring", "Days_since_review", "lat", "lng"]

Hotel_df = Hotel_df.drop(columns=columns_to_remove, errors='ignore')
Hotel_df = Hotel_df.drop_duplicates()

In [12]:

power_distance_df = pd.read_csv('/content/power_distance_nationalities_final.csv', delimiter=';')
# string split the two relevant columns to ensure no unnecessary spaces at the start or end
Hotel_df['Reviewer_Nationality'] = Hotel_df['Reviewer_Nationality'].str.strip()
power_distance_df['Reviewer_Nationality'] = power_distance_df['Reviewer_Nationality'].str.strip()

# After cleaning, use merge function to add power distance as a new column with the
# corresponding pd value based on nationality and save it into a new data frame
Hotel_df = Hotel_df.merge(power_distance_df, on='Reviewer_Nationality', how='left')
# Assuming 'Hotel_data' is your DataFrame
Hotel_df = Hotel_df.dropna(subset=['Power_Distance'])
# Get distinct nationalities that have NaN in 'Power_Distance' (i.e the ones we need to add
# to the pd dataframe in order to do a succesful and complete implementation of the pd variable)
Hotel_df

,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,Power_Distance
0,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,93.0
1,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,28.0
2,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,7.1,"[' Leisure trip ', ' Family with young childre...",3 days,38.0
3,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3 days,35.0
4,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' St...",10 days,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515207,8/30/2015,8.1,Atlantis Hotel Vienna,Kuwait,no trolly or staff to help you take the lugga...,14,2823,location,2,8,7.0,"[' Leisure trip ', ' Family with older childre...",704 day,90.0
515208,8/22/2015,8.1,Atlantis Hotel Vienna,Estonia,The hotel looks like 3 but surely not 4,11,2823,Breakfast was ok and we got earlier check in,11,12,5.8,"[' Leisure trip ', ' Family with young childre...",712 day,40.0
515209,8/19/2015,8.1,Atlantis Hotel Vienna,Egypt,The ac was useless It was a hot week in vienn...,19,2823,No Positive,0,3,2.5,"[' Leisure trip ', ' Family with older childre...",715 day,70.0
515210,8/17/2015,8.1,Atlantis Hotel Vienna,Mexico,No Negative,0,2823,The rooms are enormous and really comfortable...,25,3,8.8,"[' Leisure trip ', ' Group ', ' Standard Tripl...",717 day,81.0
515211,8/9/2015,8.1,Atlantis Hotel Vienna,Hungary,I was in 3rd floor It didn t work Free Wife,13,2823,staff was very kind,6,1,8.3,"[' Leisure trip ', ' Family with young childre...",725 day,46.0

"Naming, Hotel_df cleaned & test it"

Tokenization

In [14]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [15]:
Hotel_df['Negative_Review_tokenized'] = Hotel_df['Negative_Review'].apply(lambda x: word_tokenize(x))
Hotel_df['Positive_Review_tokenized'] = Hotel_df['Positive_Review'].apply(lambda x: word_tokenize(x))

In [ ]:
Hotel_df

Stop word removal

In [16]:
from nltk.corpus import stopwords

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
def remove_stop_words(tokens):
    stop_words = set(stopwords.words('english'))
    stop_words.discard('no')
    stop_words.discard('not')
    filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
    return filtered_tokens

Test if "No" and "Not" are not removed during stop words removal

In [19]:
Hotel_df['Negative_Review_tokenized_SWR'] = Hotel_df['Negative_Review_tokenized'].apply(remove_stop_words)
Hotel_df['Positive_Review_tokenized_SWR'] = Hotel_df['Positive_Review_tokenized'].apply(remove_stop_words)

In [ ]:
Hotel_df

POS-tagging, might be redundant based on how the code looks after lemmitization

In [20]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [21]:
from nltk import pos_tag

In [23]:
Hotel_df['Negative_Review_tokenized_SWR_POS'] = Hotel_df['Negative_Review_tokenized_SWR'].apply(lambda x: pos_tag(x))
Hotel_df['Positive_Review_tokenized_SWR_POS'] = Hotel_df['Positive_Review_tokenized_SWR'].apply(lambda x: pos_tag(x))

In [ ]:
Hotel_df

Lemmatization part

In [24]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [25]:
from nltk.stem import WordNetLemmatizer

In [26]:
lemmatizer = WordNetLemmatizer()

In [27]:
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(token) for token in tokens]

In [28]:
def lemmatize_tokens(tagged_tokens):
    lemmatized_tokens = []
    for token, pos_tag in tagged_tokens:
        pos = pos_tag[0].lower() if pos_tag else 'n'
        pos = pos if pos in ['a', 'r', 'n', 'v'] else 'n'
        lemmatized_tokens.append(lemmatizer.lemmatize(token, pos))
    return lemmatized_tokens

In [29]:
Hotel_df['Negative_Review_tokenized_SWR_POS_Lem'] = Hotel_df['Negative_Review_tokenized_SWR_POS'].apply(lemmatize_tokens)
Hotel_df['Positive_Review_tokenized_SWR_POS_Lem'] = Hotel_df['Positive_Review_tokenized_SWR_POS'].apply(lemmatize_tokens)

In [ ]:
Hotel_df

Sentiment Analysis

In [30]:
import numpy as np

In [31]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk

# Download VADER lexicon
nltk.download('vader_lexicon')

# Initialize VADER sentiment analyzer
sia = SentimentIntensityAnalyzer()

def vader_sentiment(tokens):
    text = ' '.join(tokens)  # Join list of tokens into a single string
    score = sia.polarity_scores(text)
    return score['compound']

# Load your dataset (assuming it's already loaded as Hot_df)
# Example: Hot_df = pd.read_csv('path_to_your_dataset.csv')

# Apply sentiment analysis
Hotel_df['vader_sentiment_score_positive'] = Hotel_df['Positive_Review_tokenized_SWR_POS_Lem'].apply(vader_sentiment)
Hotel_df['vader_sentiment_score_negative'] = Hotel_df['Negative_Review_tokenized_SWR_POS_Lem'].apply(vader_sentiment)

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [32]:
!pip install afinn

Requirement already satisfied: afinn in /usr/local/lib/python3.10/dist-packages (0.1)

In [33]:
import pandas as pd
from afinn import Afinn

# Initialize Afinn
afinn = Afinn()

# Function to calculate AFINN sentiment score
def afinn_sentiment(tokens):
    text = ' '.join(tokens)  # Join list of tokens into a single string
    score = afinn.score(text)
    return score

Hotel_df['afinn_sentiment_score_positive'] = Hotel_df['Positive_Review_tokenized_SWR_POS_Lem'].apply(afinn_sentiment)
Hotel_df['afinn_sentiment_score_negative'] = Hotel_df['Negative_Review_tokenized_SWR_POS_Lem'].apply(afinn_sentiment)

In [34]:
Hotel_df['combined_review'] = Hotel_df['Positive_Review_tokenized_SWR_POS_Lem'] + Hotel_df['Negative_Review_tokenized_SWR_POS_Lem']
Hotel_df['combined_afinn'] = Hotel_df['combined_review'].apply(afinn_sentiment)
Hotel_df['combined_vader'] = Hotel_df['combined_review'].apply(vader_sentiment)

In [38]:
Hotel_df

,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,...,Positive_Review_tokenized_SWR_POS_Lem,vader_sentiment_score_positive,vader_sentiment_score_negative,afinn_sentiment_score_positive,afinn_sentiment_score_negative,combined_review,combined_afinn,combined_vader,interaction_term,Power_Distance_y
0,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,...,"[park, outside, hotel, beautiful]",0.5994,-0.8819,3.0,-4.0,"[park, outside, hotel, beautiful, angry, make,...",-1.0,-0.7464,-69.4152,93.0
1,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,...,"[No, real, complaint, hotel, great, great, loc...",0.9477,-0.7096,9.0,-3.0,"[No, real, complaint, hotel, great, great, loc...",6.0,0.8910,24.9480,28.0
2,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,...,"[Location, good, staff, ok, cute, hotel, break...",0.8720,-0.4019,8.0,0.0,"[Location, good, staff, ok, cute, hotel, break...",8.0,0.8020,30.4760,38.0
3,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,...,"[Great, location, nice, surroundings, bar, res...",0.9260,-0.9394,12.0,-11.0,"[Great, location, nice, surroundings, bar, res...",1.0,-0.4418,-15.4630,35.0
4,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,...,"[Amazing, location, building, Romantic, setting]",0.7579,-0.2495,4.0,-1.0,"[Amazing, location, building, Romantic, settin...",3.0,0.6707,14.7554,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515207,8/30/2015,8.1,Atlantis Hotel Vienna,Kuwait,no trolly or staff to help you take the lugga...,14,2823,location,2,8,...,[location],0.0000,0.1280,0.0,1.0,"[location, no, trolly, staff, help, take, lugg...",1.0,0.1280,11.5200,90.0
515208,8/22/2015,8.1,Atlantis Hotel Vienna,Estonia,The hotel looks like 3 but surely not 4,11,2823,Breakfast was ok and we got earlier check in,11,12,...,"[Breakfast, ok, get, earlier, check]",0.2960,0.6597,0.0,2.0,"[Breakfast, ok, get, earlier, check, hotel, lo...",2.0,0.7650,30.6000,40.0
515209,8/19/2015,8.1,Atlantis Hotel Vienna,Egypt,The ac was useless It was a hot week in vienn...,19,2823,No Positive,0,3,...,"[No, Positive]",0.3400,-0.4215,1.0,-2.0,"[No, Positive, ac, useless, hot, week, vienna,...",-1.0,-0.1027,-7.1890,70.0
515210,8/17/2015,8.1,Atlantis Hotel Vienna,Mexico,No Negative,0,2823,The rooms are enormous and really comfortable...,25,3,...,"[room, enormous, really, comfortable, believe,...",0.5563,-0.7096,2.0,-3.0,"[room, enormous, really, comfortable, believe,...",-1.0,-0.3197,-25.8957,81.0
515211,8/9/2015,8.1,Atlantis Hotel Vienna,Hungary,I was in 3rd floor It didn t work Free Wife,13,2823,staff was very kind,6,1,...,"[staff, kind]",0.5267,0.5106,2.0,1.0,"[staff, kind, 3rd, floor, work, Free, Wife]",3.0,0.7717,35.4982,46.0

In [ ]:
# Calculate the correlation matrix
correlation_matrix = Hotel_df[['Power_Distance', 'combined_afinn']].corr()

# Print the correlation matrix
print(correlation_matrix)

In [46]:
# Assuming 'Hotel_data' is your DataFrame
# Check each column for missing values
missing_values = Hotel_df.isna().sum()

# Display the number of missing values in each column
print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
Review_Date                                      0
Average_Score                                    0
Hotel_Name                                       0
Reviewer_Nationality                             0
Negative_Review                                  0
Review_Total_Negative_Word_Counts                0
Total_Number_of_Reviews                          0
Positive_Review                                  0
Review_Total_Positive_Word_Counts                0
Total_Number_of_Reviews_Reviewer_Has_Given       0
Reviewer_Score                                   0
Tags                                             0
days_since_review                                0
Power_Distance_x                               522
Negative_Review_tokenized                        0
Positive_Review_tokenized                        0
Negative_Review_tokenized_SWR                    0
Positive_Review_tokenized_SWR                    0
Negative_Review_tokenized_SWR_POS                0
Positive_Review_tokenized_SWR_POS                0
Negative_Review_tokenized_SWR_POS_Lem            0
Positive_Review_tokenized_SWR_POS_Lem            0
vader_sentiment_score_positive                   0
vader_sentiment_score_negative                   0
afinn_sentiment_score_positive                   0
afinn_sentiment_score_negative                   0
combined_review                                  0
combined_afinn                                   0
combined_vader                                   0
interaction_term                              1428
Power_Distance_y                              1428
dtype: int64

In [43]:
print(Hotel_df)

       Review_Date  Average_Score             Hotel_Name Reviewer_Nationality  \
0         8/3/2017            7.7            Hotel Arena               Russia
1         8/3/2017            7.7            Hotel Arena              Ireland
2        7/31/2017            7.7            Hotel Arena            Australia
3        7/31/2017            7.7            Hotel Arena       United Kingdom
4        7/24/2017            7.7            Hotel Arena          New Zealand
...            ...            ...                    ...                  ...
515207   8/30/2015            8.1  Atlantis Hotel Vienna               Kuwait
515208   8/22/2015            8.1  Atlantis Hotel Vienna              Estonia
515209   8/19/2015            8.1  Atlantis Hotel Vienna                Egypt
515210   8/17/2015            8.1  Atlantis Hotel Vienna               Mexico
515211    8/9/2015            8.1  Atlantis Hotel Vienna              Hungary

                                          Negative_Review  \
0        I am so angry that i made this post available...
1                                             No Negative
2        Rooms are nice but for elderly a bit difficul...
3        My room was dirty and I was afraid to walk ba...
4        You When I booked with your company on line y...
...                                                   ...
515207   no trolly or staff to help you take the lugga...
515208           The hotel looks like 3 but surely not 4
515209   The ac was useless It was a hot week in vienn...
515210                                        No Negative
515211       I was in 3rd floor It didn t work Free Wife

        Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  \
0                                     397                     1403
1                                       0                     1403
2                                      42                     1403
3                                     210                     1403
4                                     140                     1403
...                                   ...                      ...
515207                                 14                     2823
515208                                 11                     2823
515209                                 19                     2823
515210                                  0                     2823
515211                                 13                     2823

                                          Positive_Review  \
0        Only the park outside of the hotel was beauti...
1        No real complaints the hotel was great great ...
2        Location was good and staff were ok It is cut...
3        Great location in nice surroundings the bar a...
4         Amazing location and building Romantic setting
...                                                   ...
515207                                           location
515208      Breakfast was ok and we got earlier check in
515209                                        No Positive
515210   The rooms are enormous and really comfortable...
515211                               staff was very kind

        Review_Total_Positive_Word_Counts  \
0                                      11
1                                     105
2                                      21
3                                      26
4                                       8
...                                   ...
515207                                  2
515208                                 11
515209                                  0
515210                                 25
515211                                  6

        Total_Number_of_Reviews_Reviewer_Has_Given  ...  \
0                                                7  ...
1                                                7  ...
2                                                9  ...
3                                                1  ...
4                                                3  ...
...                                            ...  ...
515207                                           8  ...
515208                                          12  ...
515209                                           3  ...
515210                                           3  ...
515211                                           1  ...

                        Positive_Review_tokenized_SWR_POS  \
0       [(park, NN), (outside, JJ), (hotel, NN), (beau...
1       [(No, DT), (real, JJ), (complaints, NNS), (hot...
2       [(Location, NN), (good, JJ), (staff, NN), (ok,...
3       [(Great, NNP), (location, NN), (nice, JJ), (su...
4       [(Amazing, VBG), (location, NN), (building, NN...
...                                                   ...
515207                                   [(location, NN)]
515208  [(Breakfast, NNP), (ok, NN), (got, VBD), (earl...
515209                        [(No, DT), (Positive, NNP)]
515210  [(rooms, NNS), (enormous, JJ), (really, RB), (...
515211                          [(staff, NN), (kind, NN)]

                    Negative_Review_tokenized_SWR_POS_Lem  \
0       [angry, make, post, available, via, possible, ...
1                                          [No, Negative]
2       [Rooms, nice, elderly, bit, difficult, room, t...
3       [room, dirty, afraid, walk, barefoot, floor, l...
4       [book, company, line, show, picture, room, thi...
...                                                   ...
515207     [no, trolly, staff, help, take, luggage, room]
515208             [hotel, look, like, 3, surely, not, 4]
515209   [ac, useless, hot, week, vienna, give, hot, air]
515210                                     [No, Negative]
515211                     [3rd, floor, work, Free, Wife]

                    Positive_Review_tokenized_SWR_POS_Lem  \
0                       [park, outside, hotel, beautiful]
1       [No, real, complaint, hotel, great, great, loc...
2       [Location, good, staff, ok, cute, hotel, break...
3       [Great, location, nice, surroundings, bar, res...
4        [Amazing, location, building, Romantic, setting]
...                                                   ...
515207                                         [location]
515208               [Breakfast, ok, get, earlier, check]
515209                                     [No, Positive]
515210  [room, enormous, really, comfortable, believe,...
515211                                      [staff, kind]

        vader_sentiment_score_positive vader_sentiment_score_negative  \
0                               0.5994                        -0.8819
1                               0.9477                        -0.7096
2                               0.8720                        -0.4019
3                               0.9260                        -0.9394
4                               0.7579                        -0.2495
...                                ...                            ...
515207                          0.0000                         0.1280
515208                          0.2960                         0.6597
515209                          0.3400                        -0.4215
515210                          0.5563                        -0.7096
515211                          0.5267                         0.5106

       afinn_sentiment_score_positive afinn_sentiment_score_negative  \
0                                 3.0                           -4.0
1                                 9.0                           -3.0
2                                 8.0                            0.0
3                                12.0                          -11.0
4                                 4.0                           -1.0
...                               ...                            ...
515207                            0.0                            1.0
515208                            0.0                            2.0
515209                            1.0                           -2.0
515210                            2.0                           -3.0
515211                            2.0                            1.0

                                          combined_review combined_afinn  \
0       [park, outside, hotel, beautiful, angry, make,...           -1.0
1       [No, real, complaint, hotel, great, great, loc...            6.0
2       [Location, good, staff, ok, cute, hotel, break...            8.0
3       [Great, location, nice, surroundings, bar, res...            1.0
4       [Amazing, location, building, Romantic, settin...            3.0
...                                                   ...            ...
515207  [location, no, trolly, staff, help, take, lugg...            1.0
515208  [Breakfast, ok, get, earlier, check, hotel, lo...            2.0
515209  [No, Positive, ac, useless, hot, week, vienna,...           -1.0
515210  [room, enormous, really, comfortable, believe,...           -1.0
515211        [staff, kind, 3rd, floor, work, Free, Wife]            3.0

       combined_vader
0             -0.7464
1              0.8910
2              0.8020
3             -0.4418
4              0.6707
...               ...
515207         0.1280
515208         0.7650
515209        -0.1027
515210        -0.3197
515211         0.7717

[514690 rows x 29 columns]

In [45]:
Hotel_df.describe()

,Average_Score,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Power_Distance,vader_sentiment_score_positive,vader_sentiment_score_negative,afinn_sentiment_score_positive,afinn_sentiment_score_negative,combined_afinn,combined_vader
count,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000
mean,8.397835,18.540838,2744.578575,17.783153,7.169121,8.395924,45.126288,0.589373,-0.206534,5.269214,-0.782774,4.486440,0.412683
std,0.547931,29.694889,2317.857771,21.807337,11.043065,1.637299,19.413205,0.340236,0.445149,5.119845,2.644991,5.878932,0.515603
min,5.200000,0.000000,43.000000,0.000000,1.000000,2.500000,0.000000,-0.983200,-0.992600,-26.000000,-37.000000,-54.000000,-0.995700
25%,8.100000,2.000000,1161.000000,5.000000,1.000000,7.500000,35.000000,0.361200,-0.709600,1.000000,-3.000000,0.000000,0.000000
50%,8.400000,9.000000,2134.000000,11.000000,3.000000,8.800000,35.000000,0.692900,-0.153100,4.000000,0.000000,3.000000,0.585900
75%,8.800000,23.000000,3633.000000,22.000000,8.000000,9.600000,50.000000,0.877900,0.000000,8.000000,0.000000,7.000000,0.857700
max,9.800000,408.000000,16670.000000,395.000000,355.000000,10.000000,104.000000,0.998800,0.994600,85.000000,38.000000,88.000000,0.998800

In [63]:

score_ranges = [(2.5, 4), (4.01, 5.5), (5.51,7 ),(7.01,8.5),(8.51,10)]  # Example ranges, adjust as needed

# Create subsets and compute correlations
correlations = {}
for i, (start, end) in enumerate(score_ranges):
    subset = Hotel_df[(Hotel_df['Reviewer_Score'] >= start) & (Hotel_df['Reviewer_Score'] <= end)]
    correlation = subset['combined_afinn'].corr(subset['Reviewer_Score'])
    correlations[f'Range {i+1} ({start}-{end})'] = correlation

# Print correlation results
for key, value in correlations.items():
    print(f"Correlation for {key}: {value}")

Correlation for Range 1 (2.5-4): 0.09788028399276584
Correlation for Range 2 (4.01-5.5): 0.12894705921614716
Correlation for Range 3 (5.51-7): 0.08859380198500763
Correlation for Range 4 (7.01-8.5): 0.11011980249796072
Correlation for Range 5 (8.51-10): 0.039765183158014396

In [57]:
import statsmodels.api as sm


# Define the IVs and DV
X = Hotel_df[['combined_vader', 'Power_Distance']]  # IVs: AFINN positive and negative sentiment scores
y = Hotel_df['Reviewer_Score']   # DV: Average Score

# Add interaction term
X['interaction_term'] = X['combined_vader'] * X['Power_Distance']

# Add a constant term to the independent variables
X = sm.add_constant(X)

# Fit the OLS model
model = sm.OLS(y, X).fit()

# Print the summary of the regression
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         Reviewer_Score   R-squared:                       0.083
Model:                            OLS   Adj. R-squared:                  0.083
Method:                 Least Squares   F-statistic:                 1.543e+04
Date:                Mon, 27 May 2024   Prob (F-statistic):               0.00
Time:                        14:39:50   Log-Likelihood:            -9.6192e+05
No. Observations:              514690   AIC:                         1.924e+06
Df Residuals:                  514686   BIC:                         1.924e+06
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                8.3082      0.007   1193.223      0.000       8.295       8.322
combined_vader       0.8261      0.011     77.075      0.000       0.805       0.847
Power_Distance      -0.0060      0.000    -44.151      0.000      -0.006      -0.006
interaction_term     0.0009      0.000      4.148      0.000       0.000       0.001
==============================================================================
Omnibus:                    62567.119   Durbin-Watson:                   1.635
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            88351.072
Skew:                          -0.958   Prob(JB):                         0.00
Kurtosis:                       3.672   Cond. No.                         286.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

<ipython-input-57-81eb043cb541>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['interaction_term'] = X['combined_vader'] * X['Power_Distance']

In [59]:
# Calculate correlation between combined_vadar and Reviewer_Score for each level of Power_Distance
correlations = Hotel_df.groupby('Power_Distance').apply(lambda x: x['combined_vader'].corr(x['Reviewer_Score']))

# Print correlation results
print("Correlation between combined_vadar and Reviewer_Score for each level of Power_Distance:")
print(correlations)

Correlation between combined_vadar and Reviewer_Score for each level of Power_Distance:
Power_Distance
0.0     -0.258790
11.0     0.190018
13.0     0.249912
18.0     0.246362
22.0     0.228924
28.0     0.268599
30.0     0.220961
31.0     0.261030
33.0     0.220666
34.0     0.253835
35.0     0.281192
38.0     0.268117
39.0     0.264009
40.0     0.255610
42.0     0.229394
44.0     0.122073
45.0     0.512115
46.0     0.250904
47.0     0.270357
49.0     0.270230
50.0     0.231455
54.0     0.240546
55.0     0.281533
56.0     0.220785
57.0     0.258561
58.0     0.271585
60.0     0.273516
61.0     0.098873
63.0     0.253849
64.0     0.217301
65.0     0.245387
66.0     0.275547
67.0     0.161322
68.0     0.276690
69.0     0.245655
70.0     0.268144
71.0     0.201819
73.0     0.222938
74.0     0.286696
75.0     0.231699
77.0     0.324243
78.0     0.223946
80.0     0.232056
81.0     0.170452
82.0    -1.000000
83.0     0.070535
85.0     0.199511
86.0     0.198182
88.0     0.233072
90.0     0.287592
92.0     0.308863
93.0     0.281069
94.0     0.226825
95.0     0.266961
97.0     0.192312
100.0    0.238822
104.0    0.236417
dtype: float64

In [62]:
score_ranges = [(2.5, 4), (4.1, 5.5), (5.6,7 ),(7.1,8.5),(8.6,10)]  # Example ranges for Reviewer_Score, adjust as needed

# Calculate correlation between combined_vadar and Reviewer_Score within each range
correlations = {}

for i, (start, end) in enumerate(score_ranges):
    subset = Hotel_df[(Hotel_df['Reviewer_Score'] >= start) & (Hotel_df['Reviewer_Score'] <= end)]
    correlation = subset['combined_vader'].corr(subset['Reviewer_Score'])
    correlations[f'Range {i+1} (Reviewer_Score {start}-{end})'] = correlation

# Print correlation results
for key, value in correlations.items():
    print(f"Correlation for {key}: {value}")

Correlation for Range 1 (Reviewer_Score 2.5-4): 0.03573330771576708
Correlation for Range 2 (Reviewer_Score 4.1-5.5): 0.12388360785395973
Correlation for Range 3 (Reviewer_Score 5.6-7): 0.0906721846129957
Correlation for Range 4 (Reviewer_Score 7.1-8.5): 0.09676682278335196
Correlation for Range 5 (Reviewer_Score 8.6-10): -0.007496212405397268

In [47]:
import statsmodels.api as sm


# Define the IVs and DV
X = Hotel_df[['combined_afinn', 'Power_Distance']]  # IVs: AFINN positive and negative sentiment scores
y = Hotel_df['Reviewer_Score']   # DV: Average Score

# Add interaction term
X['interaction_term'] = X['combined_afinn'] * X['Power_Distance']

# Add a constant term to the independent variables
X = sm.add_constant(X)

# Fit the OLS model
model = sm.OLS(y, X).fit()

# Print the summary of the regression
print(model.summary())

<ipython-input-47-f0a266db9bb8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['interaction_term'] = X['combined_afinn'] * X['Power_Distance']

                            OLS Regression Results
==============================================================================
Dep. Variable:         Reviewer_Score   R-squared:                       0.094
Model:                            OLS   Adj. R-squared:                  0.094
Method:                 Least Squares   F-statistic:                 1.770e+04
Date:                Mon, 27 May 2024   Prob (F-statistic):               0.00
Time:                        14:18:18   Log-Likelihood:            -9.5881e+05
No. Observations:              514690   AIC:                         1.918e+06
Df Residuals:                  514686   BIC:                         1.918e+06
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                8.3608      0.007   1224.820      0.000       8.347       8.374
combined_afinn       0.0644      0.001     67.429      0.000       0.063       0.066
Power_Distance      -0.0072      0.000    -53.692      0.000      -0.008      -0.007
interaction_term     0.0004      2e-05     19.026      0.000       0.000       0.000
==============================================================================
Omnibus:                    64889.637   Durbin-Watson:                   1.624
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            92501.093
Skew:                          -0.986   Prob(JB):                         0.00
Kurtosis:                       3.653   Cond. No.                     1.09e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.09e+03. This might indicate that there are
strong multicollinearity or other numerical problems.