<a href="https://colab.research.google.com/github/BIM-Master/Hotel-Reviews/blob/Sam-end-of-day-27-may/Hotel_reviews_29_sam_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2024.5.15)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.4)

In [3]:
import nltk

In [4]:
from nltk.tokenize import word_tokenize

In [5]:
import pandas as pd

In [6]:
Hotel_df = pd.read_csv("/content/Hotel_Reviews 2 (1).csv")

Removing attributes

In [7]:
columns_to_remove = ["Hotel_Address", "Additional_Number_of_Scoring", "Days_since_review", "lat", "lng"]

Hotel_df = Hotel_df.drop(columns=columns_to_remove, errors='ignore')
Hotel_df = Hotel_df.drop_duplicates()

In [10]:

power_distance_df = pd.read_csv('/content/culture_values.csv', delimiter=';')
# string split the two relevant columns to ensure no unnecessary spaces at the start or end
Hotel_df['Reviewer_Nationality'] = Hotel_df['Reviewer_Nationality'].str.strip()
power_distance_df['Reviewer_Nationality'] = power_distance_df['Reviewer_Nationality'].str.strip()



# After cleaning, use merge function to add power distance as a new column with the
# corresponding pd value based on nationality and save it into a new data frame

Hotel_df = Hotel_df.merge(power_distance_df, on='Reviewer_Nationality', how='left')

Hotel_df = Hotel_df.dropna(subset=['Power_Distance'])
# Get distinct nationalities that have NaN in 'Power_Distance' (i.e the ones we need to add
# to the pd dataframe in order to do a succesful and complete implementation of the pd variable)
Hotel_df

KeyError: ['Power_Distance']

In [11]:
Hotel_df

,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,Power_Distance_x,High_Context_x,Power_Distance_y,High_Context_y
0,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,93.0,1.0,93.0,1
1,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,28.0,0.0,28.0,0
2,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,7.1,"[' Leisure trip ', ' Family with young childre...",3 days,38.0,0.0,38.0,0
3,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3 days,35.0,0.0,35.0,0
4,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' St...",10 days,22.0,0.0,22.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514685,8/30/2015,8.1,Atlantis Hotel Vienna,Kuwait,no trolly or staff to help you take the lugga...,14,2823,location,2,8,7.0,"[' Leisure trip ', ' Family with older childre...",704 day,90.0,1.0,90.0,1
514686,8/22/2015,8.1,Atlantis Hotel Vienna,Estonia,The hotel looks like 3 but surely not 4,11,2823,Breakfast was ok and we got earlier check in,11,12,5.8,"[' Leisure trip ', ' Family with young childre...",712 day,40.0,0.0,40.0,0
514687,8/19/2015,8.1,Atlantis Hotel Vienna,Egypt,The ac was useless It was a hot week in vienn...,19,2823,No Positive,0,3,2.5,"[' Leisure trip ', ' Family with older childre...",715 day,70.0,1.0,70.0,1
514688,8/17/2015,8.1,Atlantis Hotel Vienna,Mexico,No Negative,0,2823,The rooms are enormous and really comfortable...,25,3,8.8,"[' Leisure trip ', ' Group ', ' Standard Tripl...",717 day,81.0,1.0,81.0,1
514689,8/9/2015,8.1,Atlantis Hotel Vienna,Hungary,I was in 3rd floor It didn t work Free Wife,13,2823,staff was very kind,6,1,8.3,"[' Leisure trip ', ' Family with young childre...",725 day,46.0,0.0,46.0,0

"Naming, Hotel_df cleaned & test it"

Tokenization

In [12]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [13]:
#Hotel_df['Negative_Review_tokenized'] = Hotel_df['Negative_Review'].apply(lambda x: word_tokenize(x))
#Hotel_df['Positive_Review_tokenized'] = Hotel_df['Positive_Review'].apply(lambda x: word_tokenize(x))

In [14]:
Hotel_df

,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,Power_Distance_x,High_Context_x,Power_Distance_y,High_Context_y
0,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,93.0,1.0,93.0,1
1,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,28.0,0.0,28.0,0
2,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,7.1,"[' Leisure trip ', ' Family with young childre...",3 days,38.0,0.0,38.0,0
3,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3 days,35.0,0.0,35.0,0
4,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' St...",10 days,22.0,0.0,22.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514685,8/30/2015,8.1,Atlantis Hotel Vienna,Kuwait,no trolly or staff to help you take the lugga...,14,2823,location,2,8,7.0,"[' Leisure trip ', ' Family with older childre...",704 day,90.0,1.0,90.0,1
514686,8/22/2015,8.1,Atlantis Hotel Vienna,Estonia,The hotel looks like 3 but surely not 4,11,2823,Breakfast was ok and we got earlier check in,11,12,5.8,"[' Leisure trip ', ' Family with young childre...",712 day,40.0,0.0,40.0,0
514687,8/19/2015,8.1,Atlantis Hotel Vienna,Egypt,The ac was useless It was a hot week in vienn...,19,2823,No Positive,0,3,2.5,"[' Leisure trip ', ' Family with older childre...",715 day,70.0,1.0,70.0,1
514688,8/17/2015,8.1,Atlantis Hotel Vienna,Mexico,No Negative,0,2823,The rooms are enormous and really comfortable...,25,3,8.8,"[' Leisure trip ', ' Group ', ' Standard Tripl...",717 day,81.0,1.0,81.0,1
514689,8/9/2015,8.1,Atlantis Hotel Vienna,Hungary,I was in 3rd floor It didn t work Free Wife,13,2823,staff was very kind,6,1,8.3,"[' Leisure trip ', ' Family with young childre...",725 day,46.0,0.0,46.0,0

Stop word removal

In [28]:
from nltk.corpus import stopwords

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [18]:
#def remove_stop_words(tokens):
   # stop_words = set(stopwords.words('english'))
    #stop_words.discard('no')
    #stop_words.discard('not')
    #filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
    #return filtered_tokens

Sam tokenization and stop word removal no caps and negations stay together

In [19]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')

def tokenize_and_lowercase(text):
    tokens = word_tokenize(text)
    # Convert tokens to lowercase
    tokens_lower = [token.lower() for token in tokens]
    return tokens_lower

Hotel_df['Negative_Review_tokenized'] = Hotel_df['Negative_Review'].apply(tokenize_and_lowercase)
Hotel_df['Positive_Review_tokenized'] = Hotel_df['Positive_Review'].apply(tokenize_and_lowercase)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [20]:
Hotel_df

,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,Power_Distance_x,High_Context_x,Power_Distance_y,High_Context_y,Negative_Review_tokenized,Positive_Review_tokenized
0,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,93.0,1.0,93.0,1,"[i, am, so, angry, that, i, made, this, post, ...","[only, the, park, outside, of, the, hotel, was..."
1,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,28.0,0.0,28.0,0,"[no, negative]","[no, real, complaints, the, hotel, was, great,..."
2,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,7.1,"[' Leisure trip ', ' Family with young childre...",3 days,38.0,0.0,38.0,0,"[rooms, are, nice, but, for, elderly, a, bit, ...","[location, was, good, and, staff, were, ok, it..."
3,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3 days,35.0,0.0,35.0,0,"[my, room, was, dirty, and, i, was, afraid, to...","[great, location, in, nice, surroundings, the,..."
4,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' St...",10 days,22.0,0.0,22.0,0,"[you, when, i, booked, with, your, company, on...","[amazing, location, and, building, romantic, s..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514685,8/30/2015,8.1,Atlantis Hotel Vienna,Kuwait,no trolly or staff to help you take the lugga...,14,2823,location,2,8,7.0,"[' Leisure trip ', ' Family with older childre...",704 day,90.0,1.0,90.0,1,"[no, trolly, or, staff, to, help, you, take, t...",[location]
514686,8/22/2015,8.1,Atlantis Hotel Vienna,Estonia,The hotel looks like 3 but surely not 4,11,2823,Breakfast was ok and we got earlier check in,11,12,5.8,"[' Leisure trip ', ' Family with young childre...",712 day,40.0,0.0,40.0,0,"[the, hotel, looks, like, 3, but, surely, not, 4]","[breakfast, was, ok, and, we, got, earlier, ch..."
514687,8/19/2015,8.1,Atlantis Hotel Vienna,Egypt,The ac was useless It was a hot week in vienn...,19,2823,No Positive,0,3,2.5,"[' Leisure trip ', ' Family with older childre...",715 day,70.0,1.0,70.0,1,"[the, ac, was, useless, it, was, a, hot, week,...","[no, positive]"
514688,8/17/2015,8.1,Atlantis Hotel Vienna,Mexico,No Negative,0,2823,The rooms are enormous and really comfortable...,25,3,8.8,"[' Leisure trip ', ' Group ', ' Standard Tripl...",717 day,81.0,1.0,81.0,1,"[no, negative]","[the, rooms, are, enormous, and, really, comfo..."
514689,8/9/2015,8.1,Atlantis Hotel Vienna,Hungary,I was in 3rd floor It didn t work Free Wife,13,2823,staff was very kind,6,1,8.3,"[' Leisure trip ', ' Family with young childre...",725 day,46.0,0.0,46.0,0,"[i, was, in, 3rd, floor, it, didn, t, work, fr...","[staff, was, very, kind]"

In [25]:
from nltk.corpus import stopwords

def remove_stop_words(tokens):
    stop_words = set(stopwords.words('english'))
    stop_words.discard('no')
    stop_words.discard('not')

    filtered_tokens = []
    i = 0
    while i < len(tokens):
        if tokens[i].lower() in ('not', 'no') and i + 1 < len(tokens):
            # Check if the next word is in the list of stop words
            if tokens[i+1].lower() not in stop_words:
                filtered_tokens.append(tokens[i] + ' ' + tokens[i+1])
                i += 1
            else:
                filtered_tokens.append(tokens[i] + tokens[i+1])
                i += 1
        else:
            filtered_tokens.append(tokens[i])
        i += 1

    return filtered_tokens

Test if "No" and "Not" are not removed during stop words removal

In [31]:
import nltk
from nltk.corpus import stopwords

Hotel_df['Negative_Review_tokenized_SWR'] = Hotel_df['Negative_Review_tokenized'].apply(remove_stop_words)
Hotel_df['Positive_Review_tokenized_SWR'] = Hotel_df['Positive_Review_tokenized'].apply(remove_stop_words)

In [32]:
Hotel_df

,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,...,Tags,days_since_review,Power_Distance_x,High_Context_x,Power_Distance_y,High_Context_y,Negative_Review_tokenized,Positive_Review_tokenized,Negative_Review_tokenized_SWR,Positive_Review_tokenized_SWR
0,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,...,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,93.0,1.0,93.0,1,"[i, am, so, angry, that, i, made, this, post, ...","[only, the, park, outside, of, the, hotel, was...","[i, am, so, angry, that, i, made, this, post, ...","[only, the, park, outside, of, the, hotel, was..."
1,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,...,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,28.0,0.0,28.0,0,"[no, negative]","[no, real, complaints, the, hotel, was, great,...",[no negative],"[no real, complaints, the, hotel, was, great, ..."
2,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,...,"[' Leisure trip ', ' Family with young childre...",3 days,38.0,0.0,38.0,0,"[rooms, are, nice, but, for, elderly, a, bit, ...","[location, was, good, and, staff, were, ok, it...","[rooms, are, nice, but, for, elderly, a, bit, ...","[location, was, good, and, staff, were, ok, it..."
3,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,...,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3 days,35.0,0.0,35.0,0,"[my, room, was, dirty, and, i, was, afraid, to...","[great, location, in, nice, surroundings, the,...","[my, room, was, dirty, and, i, was, afraid, to...","[great, location, in, nice, surroundings, the,..."
4,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,...,"[' Leisure trip ', ' Couple ', ' Suite ', ' St...",10 days,22.0,0.0,22.0,0,"[you, when, i, booked, with, your, company, on...","[amazing, location, and, building, romantic, s...","[you, when, i, booked, with, your, company, on...","[amazing, location, and, building, romantic, s..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514685,8/30/2015,8.1,Atlantis Hotel Vienna,Kuwait,no trolly or staff to help you take the lugga...,14,2823,location,2,8,...,"[' Leisure trip ', ' Family with older childre...",704 day,90.0,1.0,90.0,1,"[no, trolly, or, staff, to, help, you, take, t...",[location],"[no trolly, or, staff, to, help, you, take, th...",[location]
514686,8/22/2015,8.1,Atlantis Hotel Vienna,Estonia,The hotel looks like 3 but surely not 4,11,2823,Breakfast was ok and we got earlier check in,11,12,...,"[' Leisure trip ', ' Family with young childre...",712 day,40.0,0.0,40.0,0,"[the, hotel, looks, like, 3, but, surely, not, 4]","[breakfast, was, ok, and, we, got, earlier, ch...","[the, hotel, looks, like, 3, but, surely, not 4]","[breakfast, was, ok, and, we, got, earlier, ch..."
514687,8/19/2015,8.1,Atlantis Hotel Vienna,Egypt,The ac was useless It was a hot week in vienn...,19,2823,No Positive,0,3,...,"[' Leisure trip ', ' Family with older childre...",715 day,70.0,1.0,70.0,1,"[the, ac, was, useless, it, was, a, hot, week,...","[no, positive]","[the, ac, was, useless, it, was, a, hot, week,...",[no positive]
514688,8/17/2015,8.1,Atlantis Hotel Vienna,Mexico,No Negative,0,2823,The rooms are enormous and really comfortable...,25,3,...,"[' Leisure trip ', ' Group ', ' Standard Tripl...",717 day,81.0,1.0,81.0,1,"[no, negative]","[the, rooms, are, enormous, and, really, comfo...",[no negative],"[the, rooms, are, enormous, and, really, comfo..."
514689,8/9/2015,8.1,Atlantis Hotel Vienna,Hungary,I was in 3rd floor It didn t work Free Wife,13,2823,staff was very kind,6,1,...,"[' Leisure trip ', ' Family with young childre...",725 day,46.0,0.0,46.0,0,"[i, was, in, 3rd, floor, it, didn, t, work, fr...","[staff, was, very, kind]","[i, was, in, 3rd, floor, it, didn, t, work, fr...","[staff, was, very, kind]"

POS-tagging, might be redundant based on how the code looks after lemmitization

In [33]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [34]:
from nltk import pos_tag

In [35]:
Hotel_df['Negative_Review_tokenized_SWR_POS'] = Hotel_df['Negative_Review_tokenized_SWR'].apply(lambda x: pos_tag(x))
Hotel_df['Positive_Review_tokenized_SWR_POS'] = Hotel_df['Positive_Review_tokenized_SWR'].apply(lambda x: pos_tag(x))

In [36]:
Hotel_df

,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,...,Power_Distance_x,High_Context_x,Power_Distance_y,High_Context_y,Negative_Review_tokenized,Positive_Review_tokenized,Negative_Review_tokenized_SWR,Positive_Review_tokenized_SWR,Negative_Review_tokenized_SWR_POS,Positive_Review_tokenized_SWR_POS
0,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,...,93.0,1.0,93.0,1,"[i, am, so, angry, that, i, made, this, post, ...","[only, the, park, outside, of, the, hotel, was...","[i, am, so, angry, that, i, made, this, post, ...","[only, the, park, outside, of, the, hotel, was...","[(i, NN), (am, VBP), (so, RB), (angry, JJ), (t...","[(only, RB), (the, DT), (park, NN), (outside, ..."
1,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,...,28.0,0.0,28.0,0,"[no, negative]","[no, real, complaints, the, hotel, was, great,...",[no negative],"[no real, complaints, the, hotel, was, great, ...","[(no negative, JJ)]","[(no real, JJ), (complaints, NNS), (the, DT), ..."
2,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,...,38.0,0.0,38.0,0,"[rooms, are, nice, but, for, elderly, a, bit, ...","[location, was, good, and, staff, were, ok, it...","[rooms, are, nice, but, for, elderly, a, bit, ...","[location, was, good, and, staff, were, ok, it...","[(rooms, NNS), (are, VBP), (nice, JJ), (but, C...","[(location, NN), (was, VBD), (good, JJ), (and,..."
3,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,...,35.0,0.0,35.0,0,"[my, room, was, dirty, and, i, was, afraid, to...","[great, location, in, nice, surroundings, the,...","[my, room, was, dirty, and, i, was, afraid, to...","[great, location, in, nice, surroundings, the,...","[(my, PRP$), (room, NN), (was, VBD), (dirty, J...","[(great, JJ), (location, NN), (in, IN), (nice,..."
4,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,...,22.0,0.0,22.0,0,"[you, when, i, booked, with, your, company, on...","[amazing, location, and, building, romantic, s...","[you, when, i, booked, with, your, company, on...","[amazing, location, and, building, romantic, s...","[(you, PRP), (when, WRB), (i, VB), (booked, VB...","[(amazing, VBG), (location, NN), (and, CC), (b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514685,8/30/2015,8.1,Atlantis Hotel Vienna,Kuwait,no trolly or staff to help you take the lugga...,14,2823,location,2,8,...,90.0,1.0,90.0,1,"[no, trolly, or, staff, to, help, you, take, t...",[location],"[no trolly, or, staff, to, help, you, take, th...",[location],"[(no trolly, RB), (or, CC), (staff, NN), (to, ...","[(location, NN)]"
514686,8/22/2015,8.1,Atlantis Hotel Vienna,Estonia,The hotel looks like 3 but surely not 4,11,2823,Breakfast was ok and we got earlier check in,11,12,...,40.0,0.0,40.0,0,"[the, hotel, looks, like, 3, but, surely, not, 4]","[breakfast, was, ok, and, we, got, earlier, ch...","[the, hotel, looks, like, 3, but, surely, not 4]","[breakfast, was, ok, and, we, got, earlier, ch...","[(the, DT), (hotel, NN), (looks, VBZ), (like, ...","[(breakfast, NN), (was, VBD), (ok, JJ), (and, ..."
514687,8/19/2015,8.1,Atlantis Hotel Vienna,Egypt,The ac was useless It was a hot week in vienn...,19,2823,No Positive,0,3,...,70.0,1.0,70.0,1,"[the, ac, was, useless, it, was, a, hot, week,...","[no, positive]","[the, ac, was, useless, it, was, a, hot, week,...",[no positive],"[(the, DT), (ac, NN), (was, VBD), (useless, JJ...","[(no positive, JJ)]"
514688,8/17/2015,8.1,Atlantis Hotel Vienna,Mexico,No Negative,0,2823,The rooms are enormous and really comfortable...,25,3,...,81.0,1.0,81.0,1,"[no, negative]","[the, rooms, are, enormous, and, really, comfo...",[no negative],"[the, rooms, are, enormous, and, really, comfo...","[(no negative, JJ)]","[(the, DT), (rooms, NNS), (are, VBP), (enormou..."
514689,8/9/2015,8.1,Atlantis Hotel Vienna,Hungary,I was in 3rd floor It didn t work Free Wife,13,2823,staff was very kind,6,1,...,46.0,0.0,46.0,0,"[i, was, in, 3rd, floor, it, didn, t, work, fr...","[staff, was, very, kind]","[i, was, in, 3rd, floor, it, didn, t, work, fr...","[staff, was, very, kind]","[(i, NN), (was, VBD), (in, IN), (3rd, CD), (fl...","[(staff, NN), (was, VBD), (very, RB), (kind, NN)]"

Lemmatization part

In [37]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [38]:
from nltk.stem import WordNetLemmatizer

In [39]:
lemmatizer = WordNetLemmatizer()

In [40]:
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(token) for token in tokens]

In [41]:
def lemmatize_tokens(tagged_tokens):
    lemmatized_tokens = []
    for token, pos_tag in tagged_tokens:
        pos = pos_tag[0].lower() if pos_tag else 'n'
        pos = pos if pos in ['a', 'r', 'n', 'v'] else 'n'
        lemmatized_tokens.append(lemmatizer.lemmatize(token, pos))
    return lemmatized_tokens

In [42]:
Hotel_df['Negative_Review_tokenized_SWR_POS_Lem'] = Hotel_df['Negative_Review_tokenized_SWR_POS'].apply(lemmatize_tokens)
Hotel_df['Positive_Review_tokenized_SWR_POS_Lem'] = Hotel_df['Positive_Review_tokenized_SWR_POS'].apply(lemmatize_tokens)

In [43]:
Hotel_df

,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,...,Power_Distance_y,High_Context_y,Negative_Review_tokenized,Positive_Review_tokenized,Negative_Review_tokenized_SWR,Positive_Review_tokenized_SWR,Negative_Review_tokenized_SWR_POS,Positive_Review_tokenized_SWR_POS,Negative_Review_tokenized_SWR_POS_Lem,Positive_Review_tokenized_SWR_POS_Lem
0,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,...,93.0,1,"[i, am, so, angry, that, i, made, this, post, ...","[only, the, park, outside, of, the, hotel, was...","[i, am, so, angry, that, i, made, this, post, ...","[only, the, park, outside, of, the, hotel, was...","[(i, NN), (am, VBP), (so, RB), (angry, JJ), (t...","[(only, RB), (the, DT), (park, NN), (outside, ...","[i, be, so, angry, that, i, make, this, post, ...","[only, the, park, outside, of, the, hotel, be,..."
1,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,...,28.0,0,"[no, negative]","[no, real, complaints, the, hotel, was, great,...",[no negative],"[no real, complaints, the, hotel, was, great, ...","[(no negative, JJ)]","[(no real, JJ), (complaints, NNS), (the, DT), ...",[no negative],"[no real, complaint, the, hotel, be, great, gr..."
2,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,...,38.0,0,"[rooms, are, nice, but, for, elderly, a, bit, ...","[location, was, good, and, staff, were, ok, it...","[rooms, are, nice, but, for, elderly, a, bit, ...","[location, was, good, and, staff, were, ok, it...","[(rooms, NNS), (are, VBP), (nice, JJ), (but, C...","[(location, NN), (was, VBD), (good, JJ), (and,...","[room, be, nice, but, for, elderly, a, bit, di...","[location, be, good, and, staff, be, ok, it, b..."
3,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,...,35.0,0,"[my, room, was, dirty, and, i, was, afraid, to...","[great, location, in, nice, surroundings, the,...","[my, room, was, dirty, and, i, was, afraid, to...","[great, location, in, nice, surroundings, the,...","[(my, PRP$), (room, NN), (was, VBD), (dirty, J...","[(great, JJ), (location, NN), (in, IN), (nice,...","[my, room, be, dirty, and, i, be, afraid, to, ...","[great, location, in, nice, surroundings, the,..."
4,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,...,22.0,0,"[you, when, i, booked, with, your, company, on...","[amazing, location, and, building, romantic, s...","[you, when, i, booked, with, your, company, on...","[amazing, location, and, building, romantic, s...","[(you, PRP), (when, WRB), (i, VB), (booked, VB...","[(amazing, VBG), (location, NN), (and, CC), (b...","[you, when, i, book, with, your, company, on, ...","[amaze, location, and, building, romantic, set..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514685,8/30/2015,8.1,Atlantis Hotel Vienna,Kuwait,no trolly or staff to help you take the lugga...,14,2823,location,2,8,...,90.0,1,"[no, trolly, or, staff, to, help, you, take, t...",[location],"[no trolly, or, staff, to, help, you, take, th...",[location],"[(no trolly, RB), (or, CC), (staff, NN), (to, ...","[(location, NN)]","[no trolly, or, staff, to, help, you, take, th...",[location]
514686,8/22/2015,8.1,Atlantis Hotel Vienna,Estonia,The hotel looks like 3 but surely not 4,11,2823,Breakfast was ok and we got earlier check in,11,12,...,40.0,0,"[the, hotel, looks, like, 3, but, surely, not, 4]","[breakfast, was, ok, and, we, got, earlier, ch...","[the, hotel, looks, like, 3, but, surely, not 4]","[breakfast, was, ok, and, we, got, earlier, ch...","[(the, DT), (hotel, NN), (looks, VBZ), (like, ...","[(breakfast, NN), (was, VBD), (ok, JJ), (and, ...","[the, hotel, look, like, 3, but, surely, not 4]","[breakfast, be, ok, and, we, get, earlier, che..."
514687,8/19/2015,8.1,Atlantis Hotel Vienna,Egypt,The ac was useless It was a hot week in vienn...,19,2823,No Positive,0,3,...,70.0,1,"[the, ac, was, useless, it, was, a, hot, week,...","[no, positive]","[the, ac, was, useless, it, was, a, hot, week,...",[no positive],"[(the, DT), (ac, NN), (was, VBD), (useless, JJ...","[(no positive, JJ)]","[the, ac, be, useless, it, be, a, hot, week, i...",[no positive]
514688,8/17/2015,8.1,Atlantis Hotel Vienna,Mexico,No Negative,0,2823,The rooms are enormous and really comfortable...,25,3,...,81.0,1,"[no, negative]","[the, rooms, are, enormous, and, really, comfo...",[no negative],"[the, rooms, are, enormous, and, really, comfo...","[(no negative, JJ)]","[(the, DT), (rooms, NNS), (are, VBP), (enormou...",[no negative],"[the, room, be, enormous, and, really, comfort..."
514689,8/9/2015,8.1,Atlantis Hotel Vienna,Hungary,I was in 3rd floor It didn t work Free Wife,13,2823,staff was very kind,6,1,...,46.0,0,"[i, was, in, 3rd, floor, it, didn, t, work, fr...","[staff, was, very, kind]","[i, was, in, 3rd, floor, it, didn, t, work, fr...","[staff, was, very, kind]","[(i, NN), (was, VBD), (in, IN), (3rd, CD), (fl...","[(staff, NN), (was, VBD), (very, RB), (kind, NN)]","[i, be, in, 3rd, floor, it, didn, t, work, fre...","[staff, be, very, kind]"

Sentiment Analysis

In [44]:
import numpy as np

In [73]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
Hotel_df['combined_review'] = Hotel_df['Positive_Review_tokenized_SWR_POS_Lem'] + Hotel_df['Negative_Review_tokenized_SWR_POS_Lem']

# Download VADER lexicon
nltk.download('vader_lexicon')

# Initialize VADER sentiment analyzer
sia = SentimentIntensityAnalyzer()

def vader_sentiment(tokens):
    text = ' '.join(tokens)  # Join list of tokens into a single string
    score = sia.polarity_scores(text)
    return score['compound']

# Load your dataset (assuming it's already loaded as Hot_df)
# Example: Hot_df = pd.read_csv('path_to_your_dataset.csv')

# Apply sentiment analysis
Hotel_df['vader_sentiment_score_positive'] = Hotel_df['Positive_Review_tokenized_SWR_POS_Lem'].apply(vader_sentiment)
Hotel_df['vader_sentiment_score_negative'] = Hotel_df['Negative_Review_tokenized_SWR_POS_Lem'].apply(vader_sentiment)
Hotel_df['combined_vader'] = Hotel_df['combined_review'].apply(vader_sentiment)

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

KeyboardInterrupt:

In [46]:
!pip install afinn

Collecting afinn
  Downloading afinn-0.1.tar.gz (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: afinn
  Building wheel for afinn (setup.py) ... done
  Created wheel for afinn: filename=afinn-0.1-py3-none-any.whl size=53430 sha256=2cb2f89ca6ed301f81c1b68b8f84acc2875f08beb5633e0fe4e3872e0f29007b
  Stored in directory: /root/.cache/pip/wheels/b0/05/90/43f79196199a138fb486902fceca30a2d1b5228e6d2db8eb90
Successfully built afinn
Installing collected packages: afinn
Successfully installed afinn-0.1

In [47]:
import pandas as pd
from afinn import Afinn

# Initialize Afinn
afinn = Afinn()

# Function to calculate AFINN sentiment score
def afinn_sentiment(tokens):
    text = ' '.join(tokens)  # Join list of tokens into a single string
    score = afinn.score(text)
    return score

Hotel_df['afinn_sentiment_score_positive'] = Hotel_df['Positive_Review_tokenized_SWR_POS_Lem'].apply(afinn_sentiment)
Hotel_df['afinn_sentiment_score_negative'] = Hotel_df['Negative_Review_tokenized_SWR_POS_Lem'].apply(afinn_sentiment)
Hotel_df['combined_afinn'] = Hotel_df['combined_review'].apply(afinn_sentiment)

In [54]:
Hotel_df = Hotel_df.drop(columns=['Power_Distance_x', 'High_Context_x']).rename(columns={'Power_Distance_y': 'Power_Distance', 'High_Context_y': 'High_Context'})

print(Hotel_df.columns)

Index(['Review_Date', 'Average_Score', 'Hotel_Name', 'Reviewer_Nationality',
       'Negative_Review', 'Review_Total_Negative_Word_Counts',
       'Total_Number_of_Reviews', 'Positive_Review',
       'Review_Total_Positive_Word_Counts',
       'Total_Number_of_Reviews_Reviewer_Has_Given', 'Reviewer_Score', 'Tags',
       'days_since_review', 'Power_Distance', 'High_Context',
       'Negative_Review_tokenized', 'Positive_Review_tokenized',
       'Negative_Review_tokenized_SWR', 'Positive_Review_tokenized_SWR',
       'Negative_Review_tokenized_SWR_POS',
       'Positive_Review_tokenized_SWR_POS',
       'Negative_Review_tokenized_SWR_POS_Lem',
       'Positive_Review_tokenized_SWR_POS_Lem', 'combined_review',
       'vader_sentiment_score_positive', 'vader_sentiment_score_negative',
       'combined_vader', 'afinn_sentiment_score_positive',
       'afinn_sentiment_score_negative', 'combined_afinn', 'Traveler_Type',
       'Trip_Purpose'],
      dtype='object')

In [49]:
Hotel_df.describe()

,Average_Score,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Power_Distance_x,High_Context_x,Power_Distance_y,High_Context_y,vader_sentiment_score_positive,vader_sentiment_score_negative,combined_vader,afinn_sentiment_score_positive,afinn_sentiment_score_negative,combined_afinn
count,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000,514690.000000
mean,8.397835,18.540838,2744.578575,17.783153,7.169121,8.395924,45.126288,0.238777,45.126288,0.238777,0.594355,-0.192028,0.400890,5.266191,-0.780002,4.486190
std,0.547931,29.694889,2317.857771,21.807337,11.043065,1.637299,19.413205,0.426336,19.413205,0.426336,0.341618,0.459887,0.521656,5.126783,2.668043,5.899635
min,5.200000,0.000000,43.000000,0.000000,1.000000,2.500000,0.000000,0.000000,0.000000,0.000000,-0.984500,-0.997400,-0.997400,-27.000000,-38.000000,-53.000000
25%,8.100000,2.000000,1161.000000,5.000000,1.000000,7.500000,35.000000,0.000000,35.000000,0.000000,0.361200,-0.709600,0.000000,1.000000,-3.000000,0.000000
50%,8.400000,9.000000,2134.000000,11.000000,3.000000,8.800000,35.000000,0.000000,35.000000,0.000000,0.708900,-0.102700,0.571900,4.000000,0.000000,3.000000
75%,8.800000,23.000000,3633.000000,22.000000,8.000000,9.600000,50.000000,0.000000,50.000000,0.000000,0.883400,0.000000,0.849800,8.000000,0.000000,7.000000
max,9.800000,408.000000,16670.000000,395.000000,355.000000,10.000000,104.000000,1.000000,104.000000,1.000000,0.999200,0.996400,0.999300,87.000000,38.000000,89.000000

In [50]:
# add relevant tag columns
string1 = 'Couple'
string2 = 'Family with young children'
string3 = 'Group'
string4 = 'Solo traveler'
string5 = 'Family with older children'
string6 = 'Travelers with friends'

def assign_type(value):
    value = str(value)
    if string1 in value:
        return string1
    elif string2 in value:
        return string2
    elif string3 in value:
        return string3
    elif string4 in value:
        return string4
    elif string5 in value:
        return string5
    elif string6 in value:
        return string6
    else:
        return 'Other'

def assign_purpose(value):
    value = str(value)
    if 'Business trip' in value:
        return 1
    elif 'Leisure trip' in value:
        return 0
    else:
        return 'Other'

# took the last df i could find, can be renamed too
Hotel_df['Traveler_Type'] = Hotel_df['Tags'].apply(assign_type)
Hotel_df['Trip_Purpose'] = Hotel_df['Tags'].apply(assign_purpose)

TODAY

In [76]:

score_ranges = [(0, 15), (16,30 ), (31,36 ),(37,52),(53,68),(69,75),(76,90),(91,105)]  # Example ranges, adjust as needed

# Create subsets and compute correlations
correlations = {}
for i, (start, end) in enumerate(score_ranges):
    subset = Hotel_df[(Hotel_df['Power_Distance'] >= start) & (Hotel_df['Power_Distance'] <= end)]
    correlation = subset['Reviewer_Score'].corr(subset['Power_Distance'])
    correlations[f'Range {i+1} ({start}-{end})'] = correlation

# Print correlation results
for key, value in correlations.items():
    print(f"Correlation for {key}: {value}")

Correlation for Range 1 (0-15): 0.10475039575099251
Correlation for Range 2 (16-30): 0.027531817681310494
Correlation for Range 3 (31-36): 0.037214648390064387
Correlation for Range 4 (37-52): -0.06008420850729591
Correlation for Range 5 (53-68): -0.021433564232627832
Correlation for Range 6 (69-75): -0.03969646796671474
Correlation for Range 7 (76-90): -0.0445988386579185
Correlation for Range 8 (91-105): -0.0027073183688793297

In [56]:
#H0
# Calculate Pearson correlation coefficient
correlation = Hotel_df['combined_vader'].corr(Hotel_df['Reviewer_Score'])

# Print the correlation coefficient
print(f"Pearson correlation coefficient between sentiment and rating score: {correlation}")

#H0
# Calculate Pearson correlation coefficient
correlation_afinn = Hotel_df['combined_afinn'].corr(Hotel_df['Reviewer_Score'])

# Print the correlation coefficient
print(f"Pearson correlation coefficient (afinn) between sentiment and rating score: {correlation_afinn}")

Pearson correlation coefficient between sentiment and rating score: 0.28095135919257636
Pearson correlation coefficient (afinn) between sentiment and rating score: 0.295467601151458

In [77]:
#Testing H1
score_ranges = [(0, 15), (16, 30), (31, 36), (37, 52), (53, 68), (69, 75), (76, 90), (91, 105)]  # Example ranges, adjust as needed

# Create subsets and compute correlations
correlations = {}
for i, (start, end) in enumerate(score_ranges):
    subset = Hotel_df[(Hotel_df['Power_Distance'] >= start) & (Hotel_df['Power_Distance'] <= end)]
    correlation = subset['combined_afinn'].corr(subset['Reviewer_Score'])  # Assuming combined_afinn is the sentiment score column
    correlations[f'Range {i+1} ({start}-{end})'] = correlation

# Print correlation results
for key, value in correlations.items():
    print(f"Correlation (Afinn) for {key}: {value}")



# Create subsets and compute correlations
correlations_vader = {}
for i, (start, end) in enumerate(score_ranges):
    subset = Hotel_df[(Hotel_df['Power_Distance'] >= start) & (Hotel_df['Power_Distance'] <= end)]
    correlation = subset['combined_vader'].corr(subset['Reviewer_Score'])  # Assuming combined_afinn is the sentiment score column
    correlations_vader[f'Range {i+1} ({start}-{end})'] = correlation

# Print correlation results
for key, value in correlations_vader.items():
    print(f"Correlation (Vader) for {key}: {value}")
#test for significance

model = ols('Reviewer_Score ~ combined_afinn * Power_Distance', data=Hotel_df).fit()

# Perform ANOVA test
anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)

Correlation (Afinn) for Range 1 (0-15): 0.27844297361356407
Correlation (Afinn) for Range 2 (16-30): 0.28217222321621616
Correlation (Afinn) for Range 3 (31-36): 0.2891308660443252
Correlation (Afinn) for Range 4 (37-52): 0.27922096086387316
Correlation (Afinn) for Range 5 (53-68): 0.3018874779707309
Correlation (Afinn) for Range 6 (69-75): 0.29216784363857484
Correlation (Afinn) for Range 7 (76-90): 0.3039914665158879
Correlation (Afinn) for Range 8 (91-105): 0.31161232677040995
Correlation (Vader) for Range 1 (0-15): 0.24701116604671966
Correlation (Vader) for Range 2 (16-30): 0.26395933079779194
Correlation (Vader) for Range 3 (31-36): 0.2802558833266025
Correlation (Vader) for Range 4 (37-52): 0.26175080964197733
Correlation (Vader) for Range 5 (53-68): 0.2689004224220154
Correlation (Vader) for Range 6 (69-75): 0.2617559588445704
Correlation (Vader) for Range 7 (76-90): 0.2803288195062336
Correlation (Vader) for Range 8 (91-105): 0.28855917547212784
                                     sum_sq        df             F  \
combined_afinn                 1.150727e+05       1.0  47312.315677
Power_Distance                 6.532641e+03       1.0   2685.905167
combined_afinn:Power_Distance  9.490016e+02       1.0    390.183474
Residual                       1.251816e+06  514686.0           NaN

                                     PR(>F)
combined_afinn                 0.000000e+00
Power_Distance                 0.000000e+00
combined_afinn:Power_Distance  8.132025e-87
Residual                                NaN

In [82]:
#H2
# Split the dataset into high context and low context groups
high_context_group = Hotel_df[Hotel_df['High_Context'] == True]
low_context_group = Hotel_df[Hotel_df['High_Context'] == False]

# Calculate correlation between sentiments expressed and rating score for high context group
high_context_correlation = high_context_group['combined_vader'].corr(high_context_group['Reviewer_Score'])

# Calculate correlation between sentiments expressed and rating score for low context group
low_context_correlation = low_context_group['combined_vader'].corr(low_context_group['Reviewer_Score'])

# Print correlation results
print(f"Correlation for high context language cultures: {high_context_correlation}")
print(f"Correlation for low context language cultures: {low_context_correlation}")

# Compare the correlation coefficients
if high_context_correlation > low_context_correlation:
    print("High context language cultures have a stronger positive effect.")
elif high_context_correlation < low_context_correlation:
    print("Low context language cultures have a stronger positive effect.")
else:
    print("There is no significant difference between high and low context language cultures.")

#test for significance
import numpy as np
from scipy.stats import norm
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Fit a linear regression model with an interaction term
model = ols('Reviewer_Score ~ combined_vader * High_Context', data=Hotel_df).fit()
# Print the summary of the regression
print(model.summary())

# Perform ANOVA test

Correlation for high context language cultures: 0.2763524433055482
Correlation for low context language cultures: 0.2748918559296259
High context language cultures have a stronger positive effect.
                            OLS Regression Results
==============================================================================
Dep. Variable:         Reviewer_Score   R-squared:                       0.083
Model:                            OLS   Adj. R-squared:                  0.083
Method:                 Least Squares   F-statistic:                 1.554e+04
Date:                Wed, 29 May 2024   Prob (F-statistic):               0.00
Time:                        12:23:47   Log-Likelihood:            -9.6177e+05
No. Observations:              514690   AIC:                         1.924e+06
Df Residuals:                  514686   BIC:                         1.924e+06
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                       8.1132      0.003   2492.744      0.000       8.107       8.120
combined_vader                  0.8527      0.005    175.158      0.000       0.843       0.862
High_Context                   -0.2617      0.006    -42.645      0.000      -0.274      -0.250
combined_vader:High_Context     0.0442      0.010      4.572      0.000       0.025       0.063
==============================================================================
Omnibus:                    63239.839   Durbin-Watson:                   1.642
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            89628.039
Skew:                          -0.964   Prob(JB):                         0.00
Kurtosis:                       3.682   Cond. No.                         5.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [68]:
#H3 vader
trip_purposes = Hotel_df['Trip_Purpose'].unique()

# Create subsets for each trip purpose and compute correlations
correlations = {}
for purpose in trip_purposes:
    subset = Hotel_df[Hotel_df['Trip_Purpose'] == purpose]
    correlation = subset['combined_vader'].corr(subset['Reviewer_Score'])  # Assuming combined_vader is the sentiment score column
    correlations[purpose] = correlation

# Print correlation results
for purpose, correlation in correlations.items():
    print(f"Correlation(vader) for trip purpose '{purpose}': {correlation}")

#H3 afinn
trip_purposes = Hotel_df['Trip_Purpose'].unique()

# Create subsets for each trip purpose and compute correlations
correlations = {}
for purpose in trip_purposes:
    subset = Hotel_df[Hotel_df['Trip_Purpose'] == purpose]
    correlation = subset['combined_afinn'].corr(subset['Reviewer_Score'])  # Assuming combined_vader is the sentiment score column
    correlations[purpose] = correlation

# Print correlation results
for purpose, correlation in correlations.items():
    print(f"Correlation(afinn) for trip purpose '{purpose}': {correlation}")

#test for significance
# Fit a linear regression model with an interaction term
#model = ols('Reviewer_Score ~ combined_vader * Trip_Purpose', data=Hotel_df).fit()  # Replace combined_vader with combined_afinn if needed
model = ols('Reviewer_Score ~ combined_vader * C(Trip_Purpose)', data=Hotel_df).fit()

# Perform ANOVA test
anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)

X['interaction_term'] = X['combined_afinn'] * X['Trip_Purpose']

# Add a constant term to the independent variables
X = sm.add_constant(X)

# Fit the OLS model
model = sm.OLS(y, X).fit()

# Print the summary of the regression
print(model.summary())

Correlation(vader) for trip purpose '0': 0.27187399730569
Correlation(vader) for trip purpose '1': 0.2865600996385072
Correlation(vader) for trip purpose 'Other': 0.28981345580632284
Correlation(afinn) for trip purpose '0': 0.282953336189187
Correlation(afinn) for trip purpose '1': 0.3211999117616908
Correlation(afinn) for trip purpose 'Other': 0.3042334810973007
                                      sum_sq        df             F  \
C(Trip_Purpose)                 1.319678e+04       2.0   2701.198470
combined_vader                  1.028106e+05       1.0  42087.827820
combined_vader:C(Trip_Purpose)  3.946918e+02       2.0     80.787989
Residual                        1.257251e+06  514684.0           NaN

                                      PR(>F)
C(Trip_Purpose)                 0.000000e+00
combined_vader                  0.000000e+00
combined_vader:C(Trip_Purpose)  8.312434e-36
Residual                                 NaN

KeyError: 'combined_afinn'

In [ ]:
print(Hotel_df.columns)

In [69]:
#H4:
# Get unique traveler types
traveler_types = Hotel_df['Traveler_Type'].unique()

# Create subsets for each traveler type and compute correlations
correlations = {}
for traveler_type in traveler_types:
    subset = Hotel_df[Hotel_df['Traveler_Type'] == traveler_type]
    correlation = subset['combined_vader'].corr(subset['Reviewer_Score'])  # Assuming combined_vader is the sentiment score column
    correlations[traveler_type] = correlation

# Print correlation results
for traveler_type, correlation in correlations.items():
    print(f"Correlation(vader) for traveler type '{traveler_type}': {correlation}")


# Create subsets for each traveler type and compute correlations
correlations_afinn = {}
for traveler_type in traveler_types:
    subset = Hotel_df[Hotel_df['Traveler_Type'] == traveler_type]
    correlation = subset['combined_vader'].corr(subset['Reviewer_Score'])  # Assuming combined_vader is the sentiment score column
    correlations_afinn[traveler_type] = correlation

# Print correlation results
for traveler_type, correlation in correlations_afinn.items():
    print(f"Correlation(afinn) for traveler type '{traveler_type}': {correlation}")

Correlation(vader) for traveler type 'Couple': 0.26747096337607473
Correlation(vader) for traveler type 'Family with young children': 0.304974734981625
Correlation(vader) for traveler type 'Solo traveler': 0.2831874439365472
Correlation(vader) for traveler type 'Group': 0.2767657340528725
Correlation(vader) for traveler type 'Travelers with friends': 0.26165083172515863
Correlation(vader) for traveler type 'Family with older children': 0.28602832447238274
Correlation(afinn) for traveler type 'Couple': 0.26747096337607473
Correlation(afinn) for traveler type 'Family with young children': 0.304974734981625
Correlation(afinn) for traveler type 'Solo traveler': 0.2831874439365472
Correlation(afinn) for traveler type 'Group': 0.2767657340528725
Correlation(afinn) for traveler type 'Travelers with friends': 0.26165083172515863
Correlation(afinn) for traveler type 'Family with older children': 0.28602832447238274

In [60]:
#h5
# Define bins for reviewer activity levels
activity_bins = [0, 10, 20, 30, 40, 50, float('inf')]  # Example bins, adjust as needed

# Create labels for the bins
activity_labels = ['0-10', '11-20', '21-30', '31-40', '41-50', '51+']

# Create a new column to represent the bin of reviewer activity
Hotel_df['Reviewer_Activity_Bin'] = pd.cut(Hotel_df['Total_Number_of_Reviews_Reviewer_Has_Given'], bins=activity_bins, labels=activity_labels)

# Calculate correlations for each activity bin
correlations = {}
for activity_bin in activity_labels:
    subset = Hotel_df[Hotel_df['Reviewer_Activity_Bin'] == activity_bin]
    correlation = subset['combined_vader'].corr(subset['Reviewer_Score'])  # Assuming combined_vader is the sentiment score column
    correlations[activity_bin] = correlation

# Print correlation results
for activity_bin, correlation in correlations.items():
    print(f"Correlation for reviewer activity bin '{activity_bin}': {correlation}")

Correlation for reviewer activity bin '0-10': 0.2840090910464836
Correlation for reviewer activity bin '11-20': 0.27177322610546745
Correlation for reviewer activity bin '21-30': 0.26392476393478265
Correlation for reviewer activity bin '31-40': 0.24819249753299086
Correlation for reviewer activity bin '41-50': 0.27917953116707667
Correlation for reviewer activity bin '51+': 0.27263035099335725

In [59]:

score_ranges = [(2.5, 4), (4.01, 5.5), (5.51,7 ),(7.01,8.5),(8.51,10)]  # Example ranges, adjust as needed

# Create subsets and compute correlations
correlations = {}
for i, (start, end) in enumerate(score_ranges):
    subset = Hotel_df[(Hotel_df['Reviewer_Score'] >= start) & (Hotel_df['Reviewer_Score'] <= end)]
    correlation = subset['combined_afinn'].corr(subset['Reviewer_Score'])
    correlations[f'Range {i+1} ({start}-{end})'] = correlation

# Print correlation results
for key, value in correlations.items():
    print(f"Correlation for {key}: {value}")

Correlation for Range 1 (2.5-4): 0.09762824759596499
Correlation for Range 2 (4.01-5.5): 0.12700371013576764
Correlation for Range 3 (5.51-7): 0.08904680794081311
Correlation for Range 4 (7.01-8.5): 0.10922319169043729
Correlation for Range 5 (8.51-10): 0.03917751949368045

In [58]:
import statsmodels.api as sm


# Define the IVs and DV
X = Hotel_df[['combined_vader', 'Power_Distance']]  # IVs: AFINN positive and negative sentiment scores
y = Hotel_df['Reviewer_Score']   # DV: Average Score

# Add interaction term
X['interaction_term'] = X['combined_vader'] * X['Power_Distance']

# Add a constant term to the independent variables
X = sm.add_constant(X)

# Fit the OLS model
model = sm.OLS(y, X).fit()

# Print the summary of the regression
print(model.summary())

<ipython-input-58-81eb043cb541>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['interaction_term'] = X['combined_vader'] * X['Power_Distance']

                            OLS Regression Results
==============================================================================
Dep. Variable:         Reviewer_Score   R-squared:                       0.084
Model:                            OLS   Adj. R-squared:                  0.084
Method:                 Least Squares   F-statistic:                 1.566e+04
Date:                Wed, 29 May 2024   Prob (F-statistic):               0.00
Time:                        10:19:28   Log-Likelihood:            -9.6161e+05
No. Observations:              514690   AIC:                         1.923e+06
Df Residuals:                  514686   BIC:                         1.923e+06
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                8.3312      0.007   1214.981      0.000       8.318       8.345
combined_vader       0.8030      0.011     75.887      0.000       0.782       0.824
Power_Distance      -0.0062      0.000    -46.441      0.000      -0.006      -0.006
interaction_term     0.0013      0.000      6.143      0.000       0.001       0.002
==============================================================================
Omnibus:                    63247.872   Durbin-Watson:                   1.642
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            89652.781
Skew:                          -0.964   Prob(JB):                         0.00
Kurtosis:                       3.683   Cond. No.                         280.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [70]:
# Calculate correlation between combined_vadar and Reviewer_Score for each level of Power_Distance
correlations = Hotel_df.groupby('Power_Distance').apply(lambda x: x['combined_vader'].corr(x['Reviewer_Score']))

# Print correlation results
print("Correlation between combined_vadar and Reviewer_Score for each level of Power_Distance:")
print(correlations)

Correlation between combined_vadar and Reviewer_Score for each level of Power_Distance:
Power_Distance
0.0     -0.329757
11.0     0.204433
13.0     0.259044
18.0     0.248373
22.0     0.241517
28.0     0.272766
30.0     0.207006
31.0     0.265172
33.0     0.226944
34.0     0.257806
35.0     0.281478
38.0     0.269983
39.0     0.258818
40.0     0.251279
42.0     0.221053
44.0     0.156804
45.0     0.513340
46.0     0.258451
47.0     0.237063
49.0     0.262691
50.0     0.230769
54.0     0.248494
55.0     0.271970
56.0     0.215158
57.0     0.267945
58.0     0.273080
60.0     0.281258
61.0     0.119398
63.0     0.249292
64.0     0.248873
65.0     0.246592
66.0     0.283066
67.0     0.149076
68.0     0.278080
69.0     0.237196
70.0     0.273151
71.0     0.211777
73.0     0.231660
74.0     0.291625
75.0     0.240280
77.0     0.309972
78.0     0.227531
80.0     0.234481
81.0     0.171384
82.0    -1.000000
83.0     0.071932
85.0     0.192180
86.0     0.218989
88.0     0.224615
90.0     0.296523
92.0     0.321305
93.0     0.286880
94.0     0.245213
95.0     0.287144
97.0     0.229848
100.0    0.226495
104.0    0.244169
dtype: float64

In [71]:
score_ranges = [(2.5, 4), (4.1, 5.5), (5.6,7 ),(7.1,8.5),(8.6,10)]  # Example ranges for Reviewer_Score, adjust as needed

# Calculate correlation between combined_vadar and Reviewer_Score within each range
correlations = {}

for i, (start, end) in enumerate(score_ranges):
    subset = Hotel_df[(Hotel_df['Reviewer_Score'] >= start) & (Hotel_df['Reviewer_Score'] <= end)]
    correlation = subset['combined_vader'].corr(subset['Reviewer_Score'])
    correlations[f'Range {i+1} (Reviewer_Score {start}-{end})'] = correlation

# Print correlation results
for key, value in correlations.items():
    print(f"Correlation for {key}: {value}")

Correlation for Range 1 (Reviewer_Score 2.5-4): 0.05907372485878052
Correlation for Range 2 (Reviewer_Score 4.1-5.5): 0.12050009858984854
Correlation for Range 3 (Reviewer_Score 5.6-7): 0.08890068036489139
Correlation for Range 4 (Reviewer_Score 7.1-8.5): 0.09502506000539769
Correlation for Range 5 (Reviewer_Score 8.6-10): 0.002746707701905658

In [72]:
import statsmodels.api as sm


# Define the IVs and DV
X = Hotel_df[['combined_afinn', 'Power_Distance']]  # IVs: AFINN positive and negative sentiment scores
y = Hotel_df['Reviewer_Score']   # DV: Average Score

# Add interaction term
X['interaction_term'] = X['combined_afinn'] * X['Power_Distance']

# Add a constant term to the independent variables
X = sm.add_constant(X)

# Fit the OLS model
model = sm.OLS(y, X).fit()

# Print the summary of the regression
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         Reviewer_Score   R-squared:                       0.093
Model:                            OLS   Adj. R-squared:                  0.093
Method:                 Least Squares   F-statistic:                 1.753e+04
Date:                Wed, 29 May 2024   Prob (F-statistic):               0.00
Time:                        10:22:14   Log-Likelihood:            -9.5904e+05
No. Observations:              514690   AIC:                         1.918e+06
Df Residuals:                  514686   BIC:                         1.918e+06
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                8.3661      0.007   1227.034      0.000       8.353       8.379
combined_afinn       0.0631      0.001     66.334      0.000       0.061       0.065
Power_Distance      -0.0073      0.000    -54.113      0.000      -0.008      -0.007
interaction_term     0.0004   1.99e-05     19.753      0.000       0.000       0.000
==============================================================================
Omnibus:                    65169.707   Durbin-Watson:                   1.624
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            93043.014
Skew:                          -0.988   Prob(JB):                         0.00
Kurtosis:                       3.657   Cond. No.                     1.09e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.09e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

<ipython-input-72-f0a266db9bb8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['interaction_term'] = X['combined_afinn'] * X['Power_Distance']

In [78]:
import statsmodels.api as sm


# Define the IVs and DV
X = Hotel_df[['combined_vader', 'Power_Distance']]  # IVs: AFINN positive and negative sentiment scores
y = Hotel_df['Reviewer_Score']   # DV: Average Score

# Add interaction term
X['interaction_term'] = X['combined_vader'] * X['Power_Distance']

# Add a constant term to the independent variables
X = sm.add_constant(X)

# Fit the OLS model
model = sm.OLS(y, X).fit()

# Print the summary of the regression
print(model.summary())

<ipython-input-78-81eb043cb541>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['interaction_term'] = X['combined_vader'] * X['Power_Distance']

                            OLS Regression Results
==============================================================================
Dep. Variable:         Reviewer_Score   R-squared:                       0.084
Model:                            OLS   Adj. R-squared:                  0.084
Method:                 Least Squares   F-statistic:                 1.566e+04
Date:                Wed, 29 May 2024   Prob (F-statistic):               0.00
Time:                        11:57:49   Log-Likelihood:            -9.6161e+05
No. Observations:              514690   AIC:                         1.923e+06
Df Residuals:                  514686   BIC:                         1.923e+06
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                8.3312      0.007   1214.981      0.000       8.318       8.345
combined_vader       0.8030      0.011     75.887      0.000       0.782       0.824
Power_Distance      -0.0062      0.000    -46.441      0.000      -0.006      -0.006
interaction_term     0.0013      0.000      6.143      0.000       0.001       0.002
==============================================================================
Omnibus:                    63247.872   Durbin-Watson:                   1.642
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            89652.781
Skew:                          -0.964   Prob(JB):                         0.00
Kurtosis:                       3.683   Cond. No.                         280.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [83]:
import nltk
from nltk.corpus import stopwords

Hotel_df['Negative_Review_Vader_no'] = Hotel_df['Negative_Review'].apply(remove_stop_words)
Hotel_df['Positive_Review_Vader_no'] = Hotel_df['Positive_Review'].apply(remove_stop_words)

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
Hotel_df['combined_review'] = Hotel_df['Negative_Review_Vader_no'] + Hotel_df['Positive_Review_Vader_no']

# Download VADER lexicon
nltk.download('vader_lexicon')

# Initialize VADER sentiment analyzer
sia = SentimentIntensityAnalyzer()

def vader_sentiment(tokens):
    text = ' '.join(tokens)  # Join list of tokens into a single string
    score = sia.polarity_scores(text)
    return score['compound']

# Load your dataset (assuming it's already loaded as Hot_df)
# Example: Hot_df = pd.read_csv('path_to_your_dataset.csv')

# Apply sentiment analysis
Hotel_df['vader_sentiment_score_positive_no'] = Hotel_df['Positive_Review_Vader_no'].apply(vader_sentiment)
Hotel_df['vader_sentiment_score_negative_no'] = Hotel_df['Negative_Review_Vader_no'].apply(vader_sentiment)
Hotel_df['combined_vader'] = Hotel_df['combined_review'].apply(vader_sentiment)